steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'Dockerfile.simple', '-t', 'gcr.io/bitgrit-demos/n8n-app', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/bitgrit-demos/n8n-app']
images:
- 'gcr.io/bitgrit-demos/n8n-app'