FROM node:20-alpine

WORKDIR /app

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY patches ./patches
COPY packages ./packages

RUN pnpm install --frozen-lockfile --ignore-scripts
RUN pnpm build

EXPOSE 5678

CMD ["pnpm", "start"]
